<template>
  <div class="about">
    <h1>This is an about page</h1>
    <p class="paragraph"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate tempora iste error dicta veniam explicabo praesentium perferendis quibusdam assumenda libero. Officia, vero deleniti odit molestiae voluptatibus nesciunt, accusamus incidunt voluptas placeat qui quam excepturi? Ipsam repellat consequatur saepe molestias sit illo perspiciatis? Dolorum in rem voluptatem, officia doloribus itaque, eum totam quos, cum deserunt neque provident ex blanditiis quisquam! Deleniti eveniet accusantium optio reiciendis, neque quis totam autem nulla quisquam ab animi facilis saepe alias eaque tempore rerum! Quia velit fugiat reprehenderit quam minima, soluta illum ex id, hic perspiciatis voluptatum, dolores et quae repudiandae dolorum assumenda voluptatem placeat laborum.</p>
 <p class="paragraph"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate tempora iste error dicta veniam explicabo praesentium perferendis quibusdam assumenda libero. Officia, vero deleniti odit molestiae voluptatibus nesciunt, accusamus incidunt voluptas placeat qui quam excepturi? Ipsam repellat consequatur saepe molestias sit illo perspiciatis? Dolorum in rem voluptatem, officia doloribus itaque, eum totam quos, cum deserunt neque provident ex blanditiis quisquam! Deleniti eveniet accusantium optio reiciendis, neque quis totam autem nulla quisquam ab animi facilis saepe alias eaque tempore rerum! Quia velit fugiat reprehenderit quam minima, soluta illum ex id, hic perspiciatis voluptatum, dolores et quae repudiandae dolorum assumenda voluptatem placeat laborum.</p>
<p class="paragraph"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate tempora iste error dicta veniam explicabo praesentium perferendis quibusdam assumenda libero. Officia, vero deleniti odit molestiae voluptatibus nesciunt, accusamus incidunt voluptas placeat qui quam excepturi? Ipsam repellat consequatur saepe molestias sit illo perspiciatis? Dolorum in rem voluptatem, officia doloribus itaque, eum totam quos, cum deserunt neque provident ex blanditiis quisquam! Deleniti eveniet accusantium optio reiciendis, neque quis totam autem nulla quisquam ab animi facilis saepe alias eaque tempore rerum! Quia velit fugiat reprehenderit quam minima, soluta illum ex id, hic perspiciatis voluptatum, dolores et quae repudiandae dolorum assumenda voluptatem placeat laborum.</p>
 
 
  </div>
</template>
